backend:
  name: git-gateway
  branch: cms

media_folder: "static/uploads"
public_folder: "uploads"

collections:
  - label: "Home"
    name: "home"
    folder: "src/content/home"
    create: true
    delete: true
    fields:
      - {label: "Section Header", name: "title", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Image Description", name: "imageDescription", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "About"
    name: "about"
    folder: "src/content/about"
    create: true
    delete: true
    fields:
      - {label: "Name, title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Image Description", name: "imageDescription", widget: "string"}
      - {label: "Bio", name: "body", widget: "markdown"}
  - label: "Your Visit"
    name: "visit"
    folder: "src/content/visit"
    create: true
    delete: true
    fields:
      - {label: "Section Header", name: "title", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Image Description", name: "imageDescription", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
