backend:
  name: test-repo
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "Home"
    label: "home"
    files:
      - label: "Home 1"
        name: "home-1"
        file: "src/content/home-1.md"
        fields:
          - {label: "Section Header", name: "header", widget: "string", required: true}
          - {label: "Featured Image", name: "image", widget: "image", required: true}
          - {label: "Body", name: "body", widget: "markdown", required: true}
      - label: "Home 2"
        name: "home-2"
        file: "src/content/home-2.md"
        fields:
          - {label: "Section Header", name: "header", widget: "string", required: true}
          - {label: "Featured Image", name: "image", widget: "image", required: true}
          - {label: "Body", name: "body", widget: "markdown", required: true}
      - label: "Home 3"
        name: "home-3"
        file: "src/content/home-3.md"
        fields:
          - {label: "Section Header", name: "header", widget: "string", required: true}
          - {label: "Featured Image", name: "image", widget: "image", required: true}
          - {label: "Body", name: "body", widget: "markdown", required: true}
     