backend:
  name: git-gateway
  branch: cms

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "content"
    label: "Site Content"
    delete: false
    files:
      - label: "Home 1"
        name: "home-1"
        file: "src/content/home-1.md"
        fields:
          - {label: "Section Header", name: "header", widget: "string", required: true}
          - {label: "Featured Image", name: "image", widget: "image", required: true}
          - {label: "Image Description", name: "imageDescription", widget: "string", required: true}
          - {label: "Body", name: "body", widget: "markdown", required: true}
          - {label: "Title", name: "title", widget: "hidden", default: "home-1"}
      - label: "Home 2"
        name: "home-2"
        file: "src/content/home-2.md"
        fields:
          - {label: "Section Header", name: "header", widget: "string", required: true}
          - {label: "Featured Image", name: "image", widget: "image", required: true}
          - {label: "Image Description", name: "imageDescription", widget: "string", required: true}
          - {label: "Body", name: "body", widget: "markdown", required: true}
          - {label: "Title", name: "title", widget: "hidden", default: "home-2"}
      - label: "Home 3"
        name: "home-3"
        file: "src/content/home-3.md"
        fields:
          - {label: "Section Header", name: "header", widget: "string", required: true}
          - {label: "Featured Image", name: "image", widget: "image", required: true}
          - {label: "Image Description", name: "imageDescription", widget: "string", required: true}
          - {label: "Body", name: "body", widget: "markdown", required: true}
          - {label: "Title", name: "title", widget: "hidden", default: "home-3"}
     