backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - label: "Content"
    name: "content"
    folder: "src/content"
    create: true
    delete: true
    slug: "{{page}}-{{title}}"
    summary: "{{page}} | section {{order}} | {{title}}"
    fields:
      - label: "Site Page"
        name: "page"
        widget: "select"
        options: ["Home", "About", "Your Visit", "Billing & Insurance"]
      - {label: "Order", name: "order", widget: "number", valueType: "int", min: 1}
      - {label: "Section Header", name: "title", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Image Description", name: "imageDescription", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
 