backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "home-1"
    label: "Home 1"
    folder: "src/content"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Home 1", name: "home-1", widget: "markdown"}